### ISSUE TITLE
adding remix hook form breaks build

### ISSUE THREAD

**Issue by Fawwaz-2009** [forge42dev/remix-hook-form#119]
hey Alem 👋 , I made t[his re-production](https://github.com/Fawwaz-2009/remix-crypto-issue) for the issue. so first right now, it's seems that even adding a slim regular form would cause a `crypto dependency issue` go to branch `with-regular-form`

![image](https://github.com/user-attachments/assets/1964662d-8fa7-48c7-ad6f-d72e92419cf6)

you can see the error if you run `npm run dev` and refresh the page. nonetheless it does built successfully 
![image](https://github.com/user-attachments/assets/0528a3f6-e780-4a44-80bc-59a4867b8e49)

However if you are on the main branch and try to do `npm run build`, it would just fail
![image](https://github.com/user-attachments/assets/5aa1e72f-cc88-49a5-9cb7-c0abdf58395f)

**Comment by AlemTuzlak** [comment]
after going through this there is nothing that indicates this is an issue with remix-hook-form, the crypto package is not used, nor is anything from node, this must be caused by something else,  my best guess would be that here:
https://github.com/Fawwaz-2009/remix-crypto-issue/blob/main/app/actions/with-remix-hook-form.tsx#L15
you leak server only function (json) to the client bundle and that causes the crypto issue, try splitting the files up and using .server for the json utility
